/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniandes.rest.cines.dtos;

import co.edu.uniandes.sourceteam.festivalcine.entities.PeliculaEntity;
import co.edu.uniandes.sourceteam.festivalcine.entities.SalaEntity;

/**
 *
 * @author ya.bejarano10
 */
public class PeliculaDTO
{
    private Long id;
    private String nombre;
    private String anuncio;
    private String creditos;
    private int duracion ;
    private String pais;

    /**
     * Constructor por defecto
     */
    public PeliculaDTO() 
    {
        /* autogenerated method
        */ 
    }
    public PeliculaDTO(PeliculaEntity entity){
        if(entity != null)
        {
            this.id = entity.getId();
        
            this.nombre = entity.getNombre();
            this.anuncio = entity.getAnuncio();
            this.creditos = entity.getCreditos();
            this.duracion = entity.getDuracion();
            this.pais = entity.getPais();
        }
                
    }
    
    public PeliculaEntity toEntity(){
        PeliculaEntity entity = new PeliculaEntity();
        entity.setId(this.getId());
        entity.setNombre(this.getNombre());
        entity.setAnuncio(this.getAnuncio());
        entity.setCreditos(this.getCreditos());
        entity.setDuracion(this.getDuracion());
        entity.setPais(this.getPais());
        return entity;
    }
    
    /**
     * @return el nombre de la pelicula
     */
    public Long getId()
    {
        return id;
    }
    public void setId(Long idd)
    {
        id = idd;
    }
    public String getNombre()
    {
        return nombre;
    }
    
    /**
     * @param nomb nombre a establecer para la pelicula
     */
    public void setNombre(String nomb)
    {
        this.nombre = nomb;
    }

    /**
     * @return el enlace del anuncio
     */
    
    public String getAnuncio()
    {
        return anuncio;
    }
    
    /**
     * @param anun enlace nuevo del anuncio
     */
    
    public void setAnuncio(String anun)
    {
        this.anuncio = anun;
    }
    
    /**
     * @return los creditos de la pelicula
     */
    public String getCreditos() {
        return creditos;
    }

    /**
     * @param credi los nuevos creditos de la pelicula
     */
    public void setCreditos(String credi) {
        this.creditos = credi;
    }
    
    /**
     * @return la duracion de la pelicula
     */
    public int getDuracion() {
        return duracion;
    }
    
    /**
     * @param dura la duracion de la pelicula a establecer
     */
    public void setDuracion(int dura) {
        this.duracion = dura;
    }
    
    /**
     * @return el pais de la pelicula
     */
    public String getPais() {
        return pais;
    }
    
    public void setPais(String paiss) {
        this.pais = paiss;
    }
    
    
    /**
     * Convierte el objeto a una cadena
     */
    @Override
    public String toString() {
    	return "{nombre : " + getNombre()+ " duracion : " + getDuracion() + "}" ;  
    }
}
