/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniandes.rest.cines.dtos;

/**
 *
 * @author ya.bejarano10
 */
public class PeliculaDTO
{
    private Long id;
    private String nombre;
    private String anuncio;
    private String creditos;
    private int duracion ;
    private String pais;

    /**
     * Constructor por defecto
     */
    public PeliculaDTO() 
    {
        /* autogenerated method
        */ 
    }

    /**
     * Constructor con parámetros.
     * @param nomb nombre de la pelicula
     * @param anun anuncio de la pelicula
     * @param credi creditos de la pelicula
     * @param criti critico de la pelicula
     * @param dura duracion de la pelicula
     * @param paisP pais de la pelicula
     */
    public PeliculaDTO(String nomb, String anun, String credi, int dura, String paisP)
    {
		super();
                this.id = 0L;
                this.nombre = nomb;
                this.anuncio = anun;
		this.creditos = credi;
                this.duracion = dura;
                this.pais = paisP;
    }
    
    /**
     * @return el nombre de la pelicula
     */
    public Long getId()
    {
        return id;
    }
    public void setId(Long idd)
    {
        id = idd;
    }
    public String getNombre()
    {
        return nombre;
    }
    
    /**
     * @param nomb nombre a establecer para la pelicula
     */
    public void setNombre(String nomb)
    {
        this.nombre = nomb;
    }

    /**
     * @return el enlace del anuncio
     */
    
    public String getAnuncio()
    {
        return anuncio;
    }
    
    /**
     * @param anun enlace nuevo del anuncio
     */
    
    public void setAnuncio(String anun)
    {
        this.anuncio = anun;
    }
    
    /**
     * @return los creditos de la pelicula
     */
    public String getCreditos() {
        return creditos;
    }

    /**
     * @param credi los nuevos creditos de la pelicula
     */
    public void setCreditos(String credi) {
        this.creditos = credi;
    }
    
    /**
     * @return la duracion de la pelicula
     */
    public int getDuracion() {
        return duracion;
    }
    
    /**
     * @param dura la duracion de la pelicula a establecer
     */
    public void setDuracion(int dura) {
        this.duracion = dura;
    }
    
    /**
     * @return el pais de la pelicula
     */
    public String getPais() {
        return pais;
    }
    
    public void setPais(String paiss) {
        this.pais = paiss;
    }
    
    
    /**
     * Convierte el objeto a una cadena
     */
    @Override
    public String toString() {
    	return "{nombre : " + getNombre()+ " duracion : " + getDuracion() + "}" ;  
    }
}
